import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TMAWrapper from "@/components/TMAWrapper";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { EnvUnsupported } from "@/components/EnvUnsupported";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <ErrorBoundary fallback={<EnvUnsupported />}>
          <TMAWrapper>
            {children}
          </TMAWrapper>
        </ErrorBoundary>
      </body>
    </html>
  );
}
